# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ADBForwarder Debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish for linux
        run: dotnet publish -r linux-x64 -c Debug
      - name: Publish for windows
        run: dotnet publish -r win-x64 -c Debug
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ADBForwarder-linux-x64.zip
          path: ADBForwarder/bin/Debug/net8.0/linux-x64/publish
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ADBForwarder-windows-x64.zip
          path: ADBForwarder/bin/Debug/net8.0/win-x64/publish
